### ISSUE TITLE
Método setApiKey no funciona.

### ISSUE THREAD

**Issue by facuim** [situmtech/situm-cordova-plugin#34]
Desde un proyecto ionic intento realizar un setApiKey y no se ejecuta ni se injectan automaticamente los callbacks:
* @param {callback} cb - Cordova native callback to recive data.
* @param {callback} error - Cordova native callback to recive errors.
Parametros siempre indefinidos cuando se realiza el exec.

![image](https://user-images.githubusercontent.com/9051570/39446281-5cb618be-4c94-11e8-9a51-8faf3686fb96.png)
ionic info:
cli packages: (C:\Users\Facundo\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.2.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.1
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\Facundo\AppData\Local\Android\Sdk

Misc:

    backend : pro

**Comment by situmops** [comment]
Buenas tardes,

Por favor, traslade la consulta realizada a nuestro equipo de soporte en la dirección de correo electrónico: soporte@situm.es . 

Su petición será atendida tan pronto sea posible.

Muchas gracias.
